DROP DATABASE IF EXISTS IMDB;
CREATE DATABASE IF NOT EXISTS IMDB;
USE IMDB;

CREATE TABLE FILM(
    FILM_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(50),
    DESCRIPTION VARCHAR(100),
    RELEASE_YEAR YEAR
);
CREATE TABLE ACTOR(
    ACTOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50)
);

CREATE TABLE FILM_ACTOR(
    ACTOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    FILM_ID INT
);
ALTER TABLE FILM ADD LAST_UPDATE DATE AFTER RELEASE_YEAR;
ALTER TABLE ACTOR ADD LAST_UPDATE DATE AFTER LAST_NAME;


ALTER TABLE FILM_ACTOR ADD FOREIGN KEY (ACTOR_ID) REFERENCES ACTOR(ACTOR_ID);
ALTER TABLE FILM_ACTOR ADD FOREIGN KEY (FILM_ID) REFERENCES FILM(FILM_ID);

INSERT INTO FILM (TITLE, DESCRIPTION, RELEASE_YEAR) VALUES('JACK SPARROW','ASDASDASDSADASDASDAS','1994');
